export const actionTypes = {
  ADD_BASIC_POKEMONS_INFO:'ADD_BASIC_POKEMONS_INFO',
  ADD_ALL_POKEMON_DATA:'ADD_ALL_POKEMON_DATA',
  ADD_POKEMON_SELECTED:'ADD_POKEMON_SELECTED',
  SET_NEW_ERROR: 'SET_NEW_ERROR',
  REMOVE_ERROR: 'REMOVE_ERROR'
}